// Curated Institutional Credit & Macro News Feed
window.CREDIT_NEWS_DATA = [
  {
    "id": "NEWS-2026-09-01",
    "date": "2026-09-18",
    "ticker": "MACRO",
    "issuer_name": "CEMBI Broad Diversified / US Treasury Benchmark",
    "headline": "Fed Delivers 25bp Rate Cut; Front-End US Yields Rally as 2s10s Curve Steepens to +38 bps",
    "source": "Bloomberg Markets",
    "url": "https://www.bloomberg.com/markets/rates-bonds",
    "category": "Macro / Sovereign Transmission",
    "credit_impact": "Positive",
    "credit_commentary": "Front-end US Treasury easing compresses sovereign debt servicing costs across EM USD curves. High-beta CEEMEA corporate spreads benefit from tightening global liquidity conditions, providing strong refinancing windows for upcoming 2027 Eurobond maturities."
  },
  {
    "id": "NEWS-2026-09-02",
    "date": "2026-09-17",
    "ticker": "ZOREN",
    "issuer_name": "Zorlu Enerji",
    "headline": "Zorlu Enerji Completes $150M Geothermal Capacity Expansion; Affirms $132/MWh YEKDEM Floor",
    "source": "Reuters Energy",
    "url": "https://www.reuters.com/business/energy/zorlu-enerji-expansion",
    "category": "Company Specific",
    "credit_impact": "Positive",
    "credit_commentary": "Expansion directly augments dollar-linked hard-currency cash flow generation. Confirmed YEKDEM tariffs insulate the company from ongoing Turkish Lira FX volatility, improving calculated EBITDA run-rate by ~$28M annually and supporting leverage deleveraging toward 4.0x."
  },
  {
    "id": "NEWS-2026-09-03",
    "date": "2026-09-16",
    "ticker": "RAILUA",
    "issuer_name": "Ukraine Rail (Ukrzaliznytsia)",
    "headline": "EBRD & World Bank Disburse $240M Emergency Infrastructure Facility for Western Rail Corridors",
    "source": "Interfax Ukraine / EBRD Press",
    "url": "https://www.ebrd.com/news/2026/ukraine-rail-corridor-financing.html",
    "category": "Capital Markets",
    "credit_impact": "Positive",
    "credit_commentary": "Multilateral non-repayable and concessionary loan funding preserves vital liquidity buffer. While reported EBITDA reflects grant recognition ($195M in 2024), desk calculated cash EBITDA confirms operational cash breakeven; senior 2028 bond recovery floor supported at 65-70 cents."
  },
  {
    "id": "NEWS-2026-09-04",
    "date": "2026-09-15",
    "ticker": "DANGCEM",
    "issuer_name": "Dangote Refinery",
    "headline": "Dangote Refinery Reaches 500,000 bpd Run Rate; Finalizes Domestic Crude Supply Pact in Naira",
    "source": "Financial Times",
    "url": "https://www.ft.com/content/dangote-refinery-crude-naira-deal",
    "category": "Company Specific",
    "credit_impact": "Positive",
    "credit_commentary": "Transitioning crude feedstock purchases from USD to Naira eliminates acute FX mismatch on domestic refined product sales. Ramp-up to 500k bpd will drive 2026E calculated EBITDA above $1.4B, providing extensive coverage for syndicated term loan amortization."
  },
  {
    "id": "NEWS-2026-09-05",
    "date": "2026-09-14",
    "ticker": "BINGHATTI",
    "issuer_name": "Binghatti Holding",
    "headline": "Binghatti Prices $300M 3-Year Tap on 9.625% Sukuk Due 2027 at 102.25 to Fund Ultra-Luxury Pipeline",
    "source": "IFR / London Stock Exchange",
    "url": "https://www.londonstockexchange.com/news/binghatti-tap-issuance",
    "category": "Capital Markets",
    "credit_impact": "Neutral",
    "credit_commentary": "Tap pricing above par confirms robust GCC private wealth demand for branded real estate debt. However, gross leverage rises toward 2.8x; credit desk tracks off-plan escrow release milestones and collection ratios to ensure covenant compliance."
  },
  {
    "id": "NEWS-2026-09-06",
    "date": "2026-09-12",
    "ticker": "MACRO",
    "issuer_name": "Crude Oil (Brent Benchmark)",
    "headline": "Brent Crude Holds $74/bbl as OPEC+ Defers Output Hike; GCC Sovereigns Maintain Fiscal Discipline",
    "source": "S&P Global Commodity Insights",
    "url": "https://www.spglobal.com/commodityinsights/en/market-insights/latest-news/oil",
    "category": "Macro / Sovereign Transmission",
    "credit_impact": "Neutral",
    "credit_commentary": "Prices at $74/bbl remain above fiscal breakevens for Qatar and UAE (sub-$55/bbl) but slightly test Saudi Arabia's official $85/bbl breakeven. Upstream national champions (TAQA, Sonangol, KMG) generate adequate FCF; sovereign support guarantees remain rock-solid."
  },
  {
    "id": "NEWS-2026-09-07",
    "date": "2026-09-10",
    "ticker": "ESKOM",
    "issuer_name": "Eskom Holdings",
    "headline": "South Africa National Treasury Confirms Final R70bn Debt Relief Tranche Disbursed to Eskom",
    "source": "Business Day SA",
    "url": "https://www.businesslive.co.za/bd/national/eskom-debt-relief-final-tranche/",
    "category": "Rating Action",
    "credit_impact": "Positive",
    "credit_commentary": "Sovereign direct equity injection covers maturing 2026/2027 government-guaranteed bonds, eliminating near-term default hazard. Focus shifts to unbundling Transmission (NTCSA) and private grid access concessions."
  },
  {
    "id": "NEWS-2026-09-08",
    "date": "2026-09-08",
    "ticker": "SISE",
    "issuer_name": "Sisecam",
    "headline": "Sisecam Commissions $220M Flat Glass Furnace in Tarsus; European Export Share Expands to 62%",
    "source": "Bloomberg Europe",
    "url": "https://www.bloomberg.com/news/sisecam-flat-glass-expansion",
    "category": "Company Specific",
    "credit_impact": "Positive",
    "credit_commentary": "High export orientation provides natural hard-currency hedge (EUR/USD revenues) against domestic production cost inflation under Turkish IAS 29 indexation. Maintains Net Leverage below 2.0x."
  },
  {
    "id": "NEWS-2026-09-09",
    "date": "2026-09-05",
    "ticker": "IHS",
    "issuer_name": "IHS Towers",
    "headline": "IHS Towers Concludes Contract Renegotiation with MTN Nigeria; Indexation Caps FX Volatility",
    "source": "Telecoms.com",
    "url": "https://telecoms.com/526712/ihs-mtn-nigeria-contract-terms/",
    "category": "Company Specific",
    "credit_impact": "Positive",
    "credit_commentary": "Revised tower lease agreement links tariff payments directly to local diesel power costs and official NAFEM FX rates, mitigating margin dilution. FCF generation recovers toward $320M run-rate in 2026E."
  },
  {
    "id": "NEWS-2026-09-10",
    "date": "2026-09-02",
    "ticker": "MACRO",
    "issuer_name": "Central Bank of Turkey (CBRT)",
    "headline": "CBRT Holds One-Week Repo Rate at 50.0%; Reinforces Tight Monetary Stance Until Core CPI Moderates",
    "source": "Central Bank of the Republic of Turkey",
    "url": "https://www.tcmb.gov.tr/wps/wcm/connect/EN/TCMB+EN/Main+Menu/Announcements/Press+Releases",
    "category": "Macro / Sovereign Transmission",
    "credit_impact": "Watch",
    "credit_commentary": "Extended restrictive monetary conditions keep domestic TRY bank borrowing rates elevated (55-60%), incentivizing Turkish corporates (Koc, Erdemir, Zorlu) to access offshore USD Eurobond and Sukuk markets for term refinancing."
  },
  {
    "id": "NEWS-2026-09-11",
    "date": "2026-08-28",
    "ticker": "DPW",
    "issuer_name": "DP World",
    "headline": "DP World Reports 4.8% Global Throughput Growth Led by Jebel Ali & Latin American Terminals",
    "source": "Lloyd's List",
    "url": "https://www.lloydslist.com/dp-world-throughput-growth",
    "category": "Company Specific",
    "credit_impact": "Positive",
    "credit_commentary": "Strong maritime cargo volumes support high EBITDA margins (>42%). Free cash flow generation comfortably covers strategic terminal concession capex without expanding net leverage beyond management's 3.5x ceiling."
  },
  {
    "id": "NEWS-2026-09-12",
    "date": "2026-08-25",
    "ticker": "TLW",
    "issuer_name": "Tullow Oil",
    "headline": "Tullow Oil Repays $100M of 2026 Senior Notes; Ghana Jubilee Water Injection Reaches Planned Flow",
    "source": "London Stock Exchange",
    "url": "https://www.londonstockexchange.com/news/tullow-debt-paydown",
    "category": "Capital Markets",
    "credit_impact": "Positive",
    "credit_commentary": "Early open-market bond repurchases demonstrate disciplined cash flow allocation and reduce 2026 maturity wall refinancing risk. Jubilee field operational stability anchors 2026 free cash flow."
  }
];
